### ISSUE TITLE
Code not fully excecuting [Python 3.9]

### ISSUE THREAD

**Issue by NicTanghe** [byewokko/penrose#3]
Hello when i try to run your code i get the following error.

```[[ 0.17653709]
 [-0.28643555]
 [-0.41188794]
 [ 0.25870333]
 [-0.37020741]
 [-0.126369  ]
 [-0.20340349]
 [-0.31450069]
 [ 0.36367405]
 [ 0.39288645]
 [ 0.06174618]
 [-0.33816621]
 [-0.25310435]
 [-0.40584017]
 [-0.06196995]
 [ 0.08750695]
 [ 0.13676744]
 [-0.07162224]
 [-0.24839324]
 [-0.26666483]
 [-0.26166847]
 [ 0.29356813]
 [ 0.35682357]
 [ 0.02836258]
 [ 0.14971767]]
C:\Python39\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
Calculating pentagrid edges
Pentagrid edges ready
1 nodes in frontier
1 rhombs built
42 nodes in frontier
201 rhombs built
Node (1, 2, 0, -2) has only 3 neighbors. Skipping.
Node (1, 2, 1, -1) has only 3 neighbors. Skipping.
Node (2, 3, 0, -2) has only 3 neighbors. Skipping.
Node (0, 1, 0, -2) has only 3 neighbors. Skipping.
Node (0, 1, 1, -1) has only 3 neighbors. Skipping.
Node (2, 3, 1, -2) has only 2 neighbors. Skipping.
Node (3, 4, -1, -2) has only 3 neighbors. Skipping.
Node (0, 24, -1, -2) has only 3 neighbors. Skipping.
Node (0, 24, -2, -1) has only 3 neighbors. Skipping.
Node (23, 24, -2, 0) has only 3 neighbors. Skipping.
Node (23, 24, -1, 1) has only 3 neighbors. Skipping.
Node (3, 4, 0, -2) has only 3 neighbors. Skipping.
Node (3, 4, 1, -1) has only 3 neighbors. Skipping.
Node (22, 23, -2, 0) has only 3 neighbors. Skipping.
46 nodes in frontier
414 rhombs built
Node (4, 5, 0, -2) has only 3 neighbors. Skipping.
Node (4, 5, 1, -1) has only 3 neighbors. Skipping.
Node (22, 23, -1, 1) has only 3 neighbors. Skipping.
Node (21, 22, -2, 0) has only 3 neighbors. Skipping.
Node (5, 6, 0, -2) has only 3 neighbors. Skipping.
49 nodes in frontier
620 rhombs built
Node (21, 22, -1, 1) has only 3 neighbors. Skipping.
Node (20, 21, -2, 0) has only 3 neighbors. Skipping.
Node (5, 6, 1, -1) has only 3 neighbors. Skipping.
51 nodes in frontier
822 rhombs built
Node (6, 7, 0, -2) has only 3 neighbors. Skipping.
Node (20, 21, -1, 1) has only 3 neighbors. Skipping.
Node (6, 7, 1, -1) has only 3 neighbors. Skipping.
Node (19, 20, -2, 0) has only 3 neighbors. Skipping.
56 nodes in frontier
1027 rhombs built
Node (7, 8, 0, -2) has only 3 neighbors. Skipping.
Node (19, 20, -1, 1) has only 3 neighbors. Skipping.
Node (18, 19, -2, 0) has only 3 neighbors. Skipping.
65 nodes in frontier
1229 rhombs built
Node (7, 8, 1, -1) has only 3 neighbors. Skipping.
Node (8, 9, 0, -2) has only 3 neighbors. Skipping.
Node (18, 19, -1, 1) has only 3 neighbors. Skipping.
62 nodes in frontier
1433 rhombs built
Node (17, 18, -2, 0) has only 3 neighbors. Skipping.
Node (8, 9, 1, -1) has only 3 neighbors. Skipping.
Node (9, 10, 0, -2) has only 3 neighbors. Skipping.
77 nodes in frontier
1636 rhombs built
Node (17, 18, -1, 1) has only 3 neighbors. Skipping.
Node (16, 17, -2, 0) has only 3 neighbors. Skipping.
Node (9, 10, 1, -1) has only 3 neighbors. Skipping.
67 nodes in frontier
1838 rhombs built
Node (10, 11, 0, -2) has only 3 neighbors. Skipping.
Node (16, 17, -1, 1) has only 3 neighbors. Skipping.
Node (10, 11, 1, -1) has only 3 neighbors. Skipping.
61 nodes in frontier
2041 rhombs built
Node (15, 16, -2, 0) has only 3 neighbors. Skipping.
Node (11, 12, 0, -2) has only 3 neighbors. Skipping.
77 nodes in frontier
2243 rhombs built
Node (15, 16, -1, 1) has only 3 neighbors. Skipping.
Node (14, 15, -2, 0) has only 3 neighbors. Skipping.
Node (11, 12, 1, -1) has only 3 neighbors. Skipping.
75 nodes in frontier
2446 rhombs built
Node (12, 13, 0, -2) has only 3 neighbors. Skipping.
Node (14, 15, -1, 1) has only 3 neighbors. Skipping.
Node (12, 13, 1, -1) has only 3 neighbors. Skipping.
81 nodes in frontier
2649 rhombs built
Node (13, 14, -2, 0) has only 3 neighbors. Skipping.
Node (13, 14, 0, -2) has only 3 neighbors. Skipping.
Node (13, 14, -1, 1) has only 3 neighbors. Skipping.
83 nodes in frontier
2852 rhombs built
Node (13, 14, 1, -1) has only 3 neighbors. Skipping.
Node (12, 13, -2, 0) has only 3 neighbors. Skipping.
73 nodes in frontier
3054 rhombs built
Node (14, 15, 0, -2) has only 3 neighbors. Skipping.
Node (12, 13, -1, 1) has only 3 neighbors. Skipping.
72 nodes in frontier
3256 rhombs built
Node (11, 12, -2, 0) has only 3 neighbors. Skipping.
Node (14, 15, 1, -1) has only 3 neighbors. Skipping.
Node (15, 16, 0, -2) has only 3 neighbors. Skipping.
Node (11, 12, -1, 1) has only 3 neighbors. Skipping.
72 nodes in frontier
3461 rhombs built
Node (10, 11, -2, 0) has only 3 neighbors. Skipping.
Node (15, 16, 1, -1) has only 3 neighbors. Skipping.
68 nodes in frontier
3662 rhombs built
Node (16, 17, 0, -2) has only 3 neighbors. Skipping.
Node (10, 11, -1, 1) has only 3 neighbors. Skipping.
Node (9, 10, -2, 0) has only 3 neighbors. Skipping.
73 nodes in frontier
3865 rhombs built
Node (16, 17, 1, -1) has only 3 neighbors. Skipping.
Node (17, 18, 0, -2) has only 3 neighbors. Skipping.
Node (9, 10, -1, 1) has only 3 neighbors. Skipping.
64 nodes in frontier
4068 rhombs built
Node (17, 18, 1, -1) has only 3 neighbors. Skipping.
Node (8, 9, -2, 0) has only 3 neighbors. Skipping.
Node (18, 19, 0, -2) has only 3 neighbors. Skipping.
54 nodes in frontier
4271 rhombs built
Node (8, 9, -1, 1) has only 3 neighbors. Skipping.
Node (18, 19, 1, -1) has only 3 neighbors. Skipping.
Node (7, 8, -2, 0) has only 3 neighbors. Skipping.
Node (19, 20, 0, -2) has only 3 neighbors. Skipping.
Node (7, 8, -1, 1) has only 3 neighbors. Skipping.
Node (19, 20, 1, -1) has only 3 neighbors. Skipping.
43 nodes in frontier
4478 rhombs built
Node (6, 7, -2, 0) has only 3 neighbors. Skipping.
Node (20, 21, 0, -2) has only 3 neighbors. Skipping.
Node (6, 7, -1, 1) has only 3 neighbors. Skipping.
Node (20, 21, 1, -1) has only 3 neighbors. Skipping.
Node (5, 6, -2, 0) has only 3 neighbors. Skipping.
Node (21, 22, 0, -2) has only 3 neighbors. Skipping.
Node (21, 22, 1, -1) has only 3 neighbors. Skipping.
Node (5, 6, -1, 1) has only 3 neighbors. Skipping.
24 nodes in frontier
4685 rhombs built
Node (22, 23, 0, -2) has only 3 neighbors. Skipping.
Node (4, 5, -2, 0) has only 3 neighbors. Skipping.
Node (22, 23, 1, -1) has only 3 neighbors. Skipping.
Node (4, 5, -1, 1) has only 3 neighbors. Skipping.
Node (0, 24, 0, 1) has only 3 neighbors. Skipping.
Node (0, 24, 1, 0) has only 3 neighbors. Skipping.
Node (23, 24, 1, -1) has only 3 neighbors. Skipping.
Node (23, 24, 0, -2) has only 3 neighbors. Skipping.
Node (3, 4, -2, 0) has only 3 neighbors. Skipping.
Node (0, 1, -1, 1) has only 3 neighbors. Skipping.
Node (0, 1, -2, 0) has only 3 neighbors. Skipping.
Node (2, 3, -2, -1) has only 3 neighbors. Skipping.
Node (3, 4, -2, 1) has only 2 neighbors. Skipping.
Node (1, 2, -1, 1) has only 3 neighbors. Skipping.
Node (1, 2, -2, 0) has only 3 neighbors. Skipping.
Node (2, 3, -1, 1) has only 3 neighbors. Skipping.
Node (2, 3, -2, 0) has only 3 neighbors. Skipping.
Traceback (most recent call last):
  File "C:\Users\nicta\git\penroses\penrose2\ntiling.py", line 226, in <module>
    main()
  File "C:\Users\nicta\git\penroses\penrose2\ntiling.py", line 220, in main
    draw.edge(a.get_xy(homogenous=False), b.get_xy(homogenous=False), color=palette[-1], width=3)
TypeError: get_xy() got an unexpected keyword argument 'homogenous'```

**Comment by sminez** [comment]
@NicTanghe this is not the repository you have forked

**Comment by byewokko** [comment]
I did some refactoring recently and then apparently forgot to take out the `homogeneous` argument. Fixed now.

Thanks for noticing.
